version: '3.9'

services:
  web:
    build: ./api
    command: uvicorn main:app --reload --workers 3 --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/usr/src
    depends_on:
      - db
    environment:
      PYTHONPATH: /usr/src
      DB_DB: &API_DB_DB tcc
      DB_HOST: db
      DB_USER: &API_DB_USER tcc
      DB_PASS: &API_DB_PASS tcc
      DB_PORT: 5432
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - 8000:8000
  db:
    image: postgres:14.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      API_DB_DB: *API_DB_DB
      API_DB_USER: *API_DB_USER
      API_DB_PASS: *API_DB_PASS
    ports:
      - 5432:5432
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
      - ./resources/init-api-db.sh:/docker-entrypoint-initdb.d/a-init-api-db.sh