#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $API_DB_USER WITH PASSWORD '$API_DB_PASS';
    CREATE DATABASE $API_DB_DB;
    GRANT ALL PRIVILEGES ON DATABASE $API_DB_DB TO $API_DB_USER;
EOSQL